"""add lang code field

Revision ID: 5c8d5707dd3c
Revises: e8971f3868cb
Create Date: 2023-10-20 23:42:29.159877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8d5707dd3c'
down_revision = 'e8971f3868cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_code', sa.Text(), server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'language_code')
    # ### end Alembic commands ###
