"""allowed no password rooms

Revision ID: 8d3678976a5b
Revises: 26ff05dc2392
Create Date: 2023-10-22 14:43:31.208042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3678976a5b'
down_revision = '26ff05dc2392'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('room', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
