"""add rooms and characters

Revision ID: c17cf896091a
Revises: 5c8d5707dd3c
Create Date: 2023-10-21 22:03:03.237358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17cf896091a'
down_revision = '5c8d5707dd3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('participants_limit', sa.Integer(), nullable=False),
    sa.Column('participants_logged', sa.Integer(), nullable=False),
    sa.Column('adventure', sa.Enum('AI', 'EGW', 'ERLW', 'EEPC', 'GGR', 'LR', 'MOT', 'MTF', 'OGA', 'PHB', 'SCAG', 'VGM', 'TCE', 'TTP', name='adventure'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_room')),
    sa.UniqueConstraint('name', name=op.f('uq_room_name'))
    )
    op.create_table('character',
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('adventure', sa.Enum('AI', 'EGW', 'ERLW', 'EEPC', 'GGR', 'LR', 'MOT', 'MTF', 'OGA', 'PHB', 'SCAG', 'VGM', 'TCE', 'TTP', name='adventure'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_character_owner_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name=op.f('fk_character_room_id_room'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_character')),
    sa.UniqueConstraint('name', name=op.f('uq_character_name'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character')
    op.drop_table('room')
    # ### end Alembic commands ###
