"""altered type of fk in character model

Revision ID: ddf827d059f9
Revises: 3548bbcbff1d
Create Date: 2023-10-22 17:50:40.689076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf827d059f9'
down_revision = '3548bbcbff1d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room', sa.Column('room_character', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_room_room_character_character'), 'room', 'character', ['room_character'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_room_room_character_character'), 'room', type_='foreignkey')
    op.drop_column('room', 'room_character')
    # ### end Alembic commands ###
