"""reinit

Revision ID: e8971f3868cb
Revises: f2ee2fc0ff90
Create Date: 2023-10-20 18:26:59.822688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e8971f3868cb'
down_revision = 'f2ee2fc0ff90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('chat', sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('user', 'language_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('language_code', postgresql.ENUM('en', 'ru', 'UK', name='locales'), autoincrement=False, nullable=True))
    op.alter_column('user', 'is_premium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('user', 'created_at')
    op.drop_column('chat', 'last_activity')
    op.drop_column('chat', 'created_at')
    # ### end Alembic commands ###
